name: Coverage

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Use Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Installing dependencies
        run: npm ci

      - name: Coverage
        run: npm run coverage

      - name: Upload Jupiter ASM coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./packages/jupiter-asm/coverage
          flags: asm
          fail_ci_if_error: true
          verbose: true
