name: Linting

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Use Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Installing dependencies
        run: npm ci

      - name: Linting
        run: npm run lint
